name: navroutex
description: "A new Flutter project."
publish_to: "none" # Means this package is not published to pub.dev
environment:
  sdk: ^3.7.2 # Dart SDK version constraint
dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0 # Routing package for Flutter
  cupertino_icons: ^1.0.8 # iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recommended lints

flutter:
  uses-material-design: true # Enables Material Design icons, fonts, etc.
